# FROM node:20-alpine

# WORKDIR /user/src/Loteria_frontend

# COPY ./package.json .
# COPY ./package-lock.json .

# RUN npm install --include=dev

# COPY . .

# EXPOSE 3000

# CMD ["npm", "run", "start-watch"]



FROM node:20-slim

WORKDIR /user/src/Loteria_frontend

COPY ./package.json .
COPY ./package-lock.json .

RUN npm config set force true
RUN npm install --omit=optional

COPY . .

EXPOSE 5173

CMD ["npm", "run", "start"]