FROM python:3.10-slim

WORKDIR /user/src/Loteria_backend

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV PYTHONPATH="${PYTHONPATH}:/user/src/Loteria_backend"

CMD ["python3", "flask_server/server.py"]

