FROM node:18.16.0-alpine

WORKDIR /user/src/Loteria_frontend

# COPY ./package.json .
# COPY ./package-lock.json .

COPY . .

RUN npm install

# COPY . .

EXPOSE 3000

CMD ["npm", "run", "start-watch"]
